### PR TITLE
make python v3.7 compatible changes.

### PR DESCRIPTION
**Pull request by gkmngrgn**

### CODE REVIEW

**Review by isidentical — COMMENTED** [review]
I think `example.py` should stay as it is. It is complex enough and I dont want to port it to 3.7 and make it more complex. Other changes LGTM

**Comment by isidentical** [comment]
Why not directly make this a 3.6 compability patch, there are some minor things but not much (like dataclasses to `__init__` etc.)

**Comment by gkmngrgn** [comment]
@isidentical example.py is reverted. py36 fixes are waiting for you as we talked.

**Review by isidentical — APPROVED** [review]
LGTM

**Pull request merged**
